services:
  lottery-app:
    build:
       context: .
       dockerfile: Dockerfile
       args:
          - HTTP_PROXY=http://127.0.0.1:7890
          - HTTPS_PROXY=http://127.0.0.1:7890
    ports:
      - "3000:3000"  
    volumes:
      - lottery-data:/app/data  # 持久化数据库
    restart: unless-stopped
    environment:
      - NODE_ENV=production

volumes:
  lottery-data:
